Make ShellCheck happy

diff --git a/lib/github-command-upload b/lib/github-command-upload
--- a/lib/github-command-upload
+++ b/lib/github-command-upload
@@ -4,7 +4,7 @@
 # command
 #
 # First argument is expected to be a command file path, already
-# verified against trusted keys set. 
+# verified against trusted keys set.
 
 if [ $# -lt 1 ]; then
     echo "Usage: $0 <command-file>" >&2
@@ -15,9 +15,10 @@ command_file="$1"
 
 scripts_dir="/usr/local/lib/qubes-builder-github"
 
+# shellcheck source=lib/functions.sh
 . "$scripts_dir/functions.sh"
 
-read action component commit_sha release_name repo_name dists_and_end \
+read -r action component commit_sha release_name repo_name dists_and_end \
         < "$command_file"
 
 if [ "x$action" != "xUpload" ]; then
@@ -46,7 +47,7 @@ case "${dists_and_end}" in
         ;;
 esac
 
-if [ "x$repo_name" != "xcurrent" -a "x$repo_name" != "xsecurity-testing" ]; then
+if [ "x$repo_name" != "xcurrent" ] && [ "x$repo_name" != "xsecurity-testing" ]; then
     echo "Unsupported target repo" >&2
     exit 1
 fi
@@ -55,74 +56,74 @@ fi
 export QUBES_BUILD_LOG_CMD="qrexec-client-vm 'dom0' qubesbuilder.BuildLog"
 
 upload_for_release() {
-    local config_release_name="$1"
-    local builder_dir="$2"
+    local_config_release_name="$1"
+    local_builder_dir="$2"
 
-    if [ "$config_release_name" != "$release_name" ]; then
+    if [ "$local_config_release_name" != "$release_name" ]; then
         return
     fi
 
-    if ! [ -d "$builder_dir/qubes-src/$component" ]; then
-        echo "Component $component not found in $builder_dir" >&2
+    if ! [ -d "$local_builder_dir/qubes-src/$component" ]; then
+        echo "Component $component not found in $local_builder_dir" >&2
         # maybe it's in another VM?
         return 0
     fi
 
-    actual_commit_sha=$(git -C "$builder_dir/qubes-src/$component" rev-parse HEAD)
+    actual_commit_sha=$(git -C "$local_builder_dir/qubes-src/$component" rev-parse HEAD)
     if [ "x$commit_sha" != "x$actual_commit_sha" ]; then
         echo "Repository have changed in the meantime (current: $actual_commit_sha)" >&2
         return 1
     fi
 
     # if no specific distribution was requested, upload all of them
-    if [ "x$dists_and_end" == "xrepo" ]; then
+    if [ "x$dists_and_end" = "xrepo" ]; then
         COMPONENTS="$component" \
-        "$builder_dir/scripts/make-with-log" \
-            update-repo-$repo_name
+        "$local_builder_dir/scripts/make-with-log" \
+            "update-repo-$repo_name"
         return $?
     fi
 
     # otherwise, process repositories list
     requested_dists_dom0=
     requested_dists_vm=
-    supported_dists_dom0=$(make --no-print-directory -C "$builder_dir" \
+    supported_dists_dom0=$(make --no-print-directory -C "$local_builder_dir" \
             get-var GET_VAR=DIST_DOM0)
-    supported_dists_vm=$(make --no-print-directory -C "$builder_dir" \
+    supported_dists_vm=$(make --no-print-directory -C "$local_builder_dir" \
             get-var GET_VAR=DISTS_VM_NO_FLAVOR)
     IFS=' '
     for dist_pair in $dists_and_end; do
         package_set=${dist_pair%%-*}
         dist=${dist_pair#*-}
-        if [ "x$package_set" == "xdom0" ]; then
+        if [ "x$package_set" = "xdom0" ]; then
             if echo " $supported_dists_dom0 " | grep -q " $dist "; then
                 requested_dists_dom0="$requested_dists_dom0 $dist"
             fi
             # don't fail otherwise - maybe builder in other VM will handle it
-        elif [ "x$package_set" == "xvm" ]; then
+        elif [ "x$package_set" = "xvm" ]; then
             if echo " $supported_dists_vm " | grep -q " $dist "; then
                 requested_dists_vm="$requested_dists_vm $dist"
             fi
             # don't fail otherwise - maybe builder in other VM will handle it
-        elif [ "x$dist_pair" == "xrepo" ]; then
+        elif [ "x$dist_pair" = "xrepo" ]; then
             # end processing here
             break
         fi
     done
 
     # strip leading spaces
-    read requested_dists_vm <<EOF
+    read -r requested_dists_vm <<EOF
 $requested_dists_vm
 EOF
-    read requested_dists_dom0 <<EOF
+    read -r requested_dists_dom0 <<EOF
 $requested_dists_dom0
 EOF
 
-    if [ -n "$requested_dists_vm" -o -n "$requested_dists_dom0" ]; then
+    if [ -n "$requested_dists_vm$requested_dists_dom0" ]; then
         COMPONENTS="$component" \
         DISTS_VM="$requested_dists_vm" \
         DIST_DOM0="$requested_dists_dom0" \
-        "$builder_dir/scripts/make-with-log" \
-            update-repo-$repo_name
+        "$local_builder_dir/scripts/make-with-log" \
+            "update-repo-$repo_name"
         return $?
     fi
 }
